### PR TITLE
Intelligently update blocks in gitignore

### PR DESCRIPTION
**Pull request by nottrobin**
If a `.gitignore` file exists in the project, compare the blocks in the
file with the gitignore template and if blocks with the same IDs exist,
then replace them.

QA
--

``` bash
sudo npm link   # Use this version of generator-canonical-webteam
git clone https://github.com/canonical-websites/tour.ubuntu.com  # Experiment with tour
cd tour.ubuntu.com
yo canonical-webteam:run
```

Now answer `Y` to replacing the `.gitignore` file. Inspect the new file, and see all the new blocks from https://gist.github.com/nottrobin/38a484926513173e6ec0511999f07f6c are there, but that the old ignore rules remain below.

Now edit `.gitignore`, and change one of the new blocks.

Run `yo canonical-webteam:run` again to replace the .gitignore again. See that your changes are replaced.

### CODE REVIEW

**Comment by nottrobin** [comment]
[Update gitignore more intellegently](https://trello.com/c/ZLUQc4sg/3305-update-gitignore-more-intellegently)

**Review by WillMoggridge — CHANGES_REQUESTED** [review]
It works well but does remove the newline from the end of the file. Could this be updated to prevent that?

**Comment by nottrobin** [comment]
@WillMoggridge with the way that this works it's difficult to *keep* the existing newline, as such, but I have made it so it *always* adds a newline to the end. Does that sound okay to you?

**Comment by WillMoggridge** [comment]
Hmmmm... Maybe leaving it as deleting the newline is best for now and we can try to revisit it.
I don't mind if we just leave it as adding the new line, though. I'll approve it.

**Review by WillMoggridge — APPROVED** [review]

**Comment by nottrobin** [comment]
okay removed that commit. merging.

**Pull request merged**
