### PR TITLE
Add a DB version of the run-django script

### PR DESCRIPTION
**Pull request by nottrobin**
Merge #2 first.

Extend the ./run script, similar to `run-django`

QA
--

Merge #2 first.

Prepare:

``` bash
sudo npm install -g yo  # You need Yeoman
sudo npm link  # Link this branch
cd ..
git clone https://github.com/canonical-websites/partners.ubuntu.com  # Get ubuntu.com project
cd partners.ubuntu.com
```

Add generate run script for www.ubuntu.com to overwrite existing one:

``` bash
yo canonical-webteam:run-django-db --force
```

Now try out all the script functions:

``` bash
./run --help
./run
./run start --watch --detach
./run django shell
./run stop
./run clean
./run <other things>
```

### CODE REVIEW

**Comment by nottrobin** [comment]
[Generator for the run script](https://trello.com/c/s9lyIH3w/3083-generator-for-the-run-script)

**Review by WillMoggridge — CHANGES_REQUESTED** [review]
Seem to be missing the network creation step such as this from partners.
```
    # First create isolated network if it doesn't exist
    if ! docker network inspect ${network} &> /dev/null; then
        docker network create ${network}
    fi
```

**Comment by nottrobin** [comment]
@WillMoggridge you're not wrong. Adding now...

**Review by WillMoggridge — APPROVED** [review]
Looks good

**Pull request merged**
