### PR TITLE
Add a basic run script for NPM-based projects

### PR DESCRIPTION
**Pull request by nottrobin**
This builds on the run script in www.ubuntu.com and other projects.

It was initially added here by @nottrobin:
https://github.com/canonical-websites/www.ubuntu.com/pull/1411

And improved on by @WillMoggridge to add Yarn caching, namespacing of containers and detaching capability:
https://github.com/canonical-websites/www.ubuntu.com/pull/1459
https://github.com/canonical-websites/www.ubuntu.com/pull/1478

And further shores up the script with the following tweaks:

- Better encapsulating functions for running docker with specific
  settings
- Improve namespacing of containers so each container type has its own
  name - this prevents new `yarn` containers from killing existing
  containers except where appropriate (hopefully)
- Make `--detach` into an option on `./run start`, instead of a global
  option

QA
--

Install `yo`, link this branch and then create a dummy project directory with a package.json:

``` bash
sudo npm install -g yo
sudo npm link
cd ../
mkdir test-project
cd test-project
curl -s https://pastebin.com/raw/E2vy80Wx > package.json
```

Now run the generator:

``` bash
yo canonical-webteam      # See the help
yo canonical-webteam:run  # Install the ./run script
```

Test out the run script, check it makes sense:

``` bash
./run --help
./run
./run start --watch
./run start --detach
./run <other-things>
```

### CODE REVIEW

**Review by barrymcgee — APPROVED** [review]
LGTM

**Comment by nottrobin** [comment]
[Generator for the run script](https://trello.com/c/s9lyIH3w/3083-generator-for-the-run-script)

**Comment by WillMoggridge** [comment]
@nottrobin It is looking nice and clean but I realise there isn't any logic for port forwarding. I would imagine that is needed?

**Comment by nottrobin** [comment]
@WillMoggridge I see what you mean, we have `./run start` (which I should now be renaming to `./run serve`) which is expected to run a server.

Although I'm now working on a separate script to run a Jekyll server, with an image to manage ruby dependencies (see #6), so I'm thinking this basic Node-only run script doesn't really need a `serve` or `start` end-point. I'll remove it.

**Comment by WillMoggridge** [comment]
@nottrobin A Polymer project would be suited to serve from this base script, I don't think we should remove that function.

**Comment by nottrobin** [comment]
@WillMoggridge good point. I'll rename it to `serve` and add a `--port` option.

**Comment by WillMoggridge** [comment]
Awesome :)

**Comment by nottrobin** [comment]
@WillMoggridge I've done that, but I don't have a good project to test it with. Could you? Make sure you test `./run serve --port XXXX` as well.

**Review by WillMoggridge — APPROVED** [review]
OK, this is looking good :)

**Pull request merged**
