### PR TITLE
2.6.2: Allow multiple exposed ports in exec; Fix module volumes

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

**Module volumes**

Get yourself a checkout of [vanilla-framework](https://github.com/vanilla-framework/vanilla-framework/) which contains an obvious change that will effect the styling of www.ubuntu.com.

Now run the site with:

``` bash
./run --node-module $HOME/{path-to-projects-folder}/vanilla-framework
.. or ..
./run -m $HOME/{path-to-projects-folder}/vanilla-framework
```

Visit the site on http://0.0.0.0:8001 and check it's clearly running your version of vanilla-framework

**Expose multiple ports**

Check you can expose multiple ports from a container:

``` bash
./run build  # Make sure dependencies are installed, to make Will happy
./run exec --env SOME_VAR=hello --export-port 8001 -p 8901
$ echo $SOME_VAR
$ ./manage.py runserver 0.0.0.0:8001 & ./manage.py runserver 0.0.0.0:8901
```

Check you can access the site both at http://0.0.0.0:8001 and http://0.0.0.0:8901.

### CODE REVIEW

**Comment by tbille** [comment]
@nottrobin we already implemented the possiblity for a user to deply multiple ports: if you add this environment variable: `EXTRA_PORTS='8000,8001,8002'`

**Comment by nottrobin** [comment]
@tbille that's only for `./run serve`. This is for `./run exec`. `exec` doesn't get the default environment variables, it simply runs you a basic session inside the docker image.  This then allows you to explicitly pass environment variables to `exec` for testing.

**Review by WillMoggridge — CHANGES_REQUESTED** [review]
In both cases, this works if you already have dependencies (ie, run the server before) installed but fails if you do not.

For node module volumes, if you do not have the `node_modules/[MODULE]` folders, it will create them as root and error a moment later from permissions.

For exec, it doesn't check for requirements to install/update. So you don't have any packages installed that you may need.

**Comment by nottrobin** [comment]
@WillMoggridge I've updated the QA steps. Yes `exec` doesn't worry about dependencies. This is deliberate - it's supposed to be a naive way of running something inside the container, not doing any extra stuff.

If running `./run exec` creates a `node_modules` folder (as root or otherwise) than that's a bug, but not related to this PR, so please file it as a separate issue.

**Comment by WillMoggridge** [comment]
@nottrobin OK, the exec dependencies can be look at away from this PR.

As for creating node modules as a root owned folder, it is a problem when running `./run --node-module $HOME/{path-to-projects-folder}/vanilla-framework` in a clean directory (or after ./run clean).

**Comment by nottrobin** [comment]
Ah! Yes that's an actual problem with this PR. Cool

**Comment by nottrobin** [comment]
Ah! Yes that's an actual problem with this PR. Cool

**Comment by nottrobin** [comment]
@WillMoggridge very good catch. Sorry for misunderstanding you initially.

I've fixed the issue in https://github.com/canonical-webteam/generator-canonical-webteam/pull/58/commits/ecf1aa9857d2a2dc2a926be5980d78576ec140b9. Please check?

**Review by WillMoggridge — APPROVED** [review]
Awesome, looks good! 👌

**Comment by nottrobin** [comment]
This still had an issue related to https://github.com/canonical-webteam/generator-canonical-webteam/issues/59 - namely that if you first install dependencies with a module override in place, it then won't bother installing that dependency later, if you then don't have the override in place.

But that should be fixed separately.

**Pull request merged**
