### PR TITLE
Create or update the package.json file.

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

Merge #1 first.

``` bash
sudo npm install -g yo  # You need Yeoman
sudo npm link  # Link this branch

cd ..
git clone https://github.com/canonical-websites/partners.ubuntu.com  # Get ubuntu.com project
cd partners.ubuntu.com

yo canonical-webteam:run

git diff
```

### CODE REVIEW

**Comment by nottrobin** [comment]
[Generator for the run script](https://trello.com/c/s9lyIH3w/3083-generator-for-the-run-script)

**Comment by barrymcgee** [comment]
I errored out at `yo canonical-webteam:run` ?

screen shot 2017-04-12 at 13 12 42

**Comment by nottrobin** [comment]
@barrymcgee that's odd. I've just rebased from master, maybe that helped? Try deleting your local branch, re-syncing, running `npm link` again, and see if you still get the error? If you do we can debug together.

**Comment by barrymcgee** [comment]
@nottrobin Got a little further - I'm assuming I should be answering 'yes' to those questions?

screen shot 2017-04-12 at 14 17 18

**Comment by nottrobin** [comment]
Sorry @barrymcgee, bad merge. Try again now.

Yes you should be answering "yes", and then doing "git diff" to see all the stuff it did to the project files.

**Comment by barrymcgee** [comment]
Looks like it's working now - https://cl.ly/2t3v3211232H

**Review by barrymcgee — APPROVED** [review]

**Pull request merged**
