### PR TITLE
Run script for jekyll sites

### LINKED ISSUE #6: Add a run-jekyll script for projects which rely on Jekyll
How much of a future do Jekyll-based solutions have in our team? It would be nice if we could keep our stacks to purely Python and NodeJS. However, if it does have to include Ruby as well, in the long term, then we should create a standard and container for running Jekyll through Ruby Bundler, the same way as we have for Django (in #2).

If, however, we think Jekyll only has a limited life until we find a better solution, then it might be more expedient to simply create a zombie version of the Yarn image which includes Ruby and Jekyll hard-wired into it.

### PR DESCRIPTION
**Pull request by nottrobin**
Make use of canonicalwebteam/bundler to manage ruby dependencies and run
a jekyll site, much like how we do Django sites.

Resolves #6.

QA
--

Do the usual stuff to install this:

``` bash
sudo npm install -g yo
sudo npm link
```

Now go and checkout vanilla-framework, run the generator but reject the `package.json` updates:

``` bash
$ yo canonical-webteam:run-jekyll
? Should we update .gitignore? Yes
? Should we update "devDependencies" in package.json? No
? Should we update "scripts" in package.json? No
 conflict run
? Overwrite run? overwrite
 force run
```

Add some scripts build script to `package.json` as follows:

``` json
  "scripts": {
    "clean": "rm -rf node_modules yarn-error.log",
    "build": "gulp build"
  }
```

Now test it out:

``` bash
./run
./run --help
./run build
./run watch --watch-site
```

### CODE REVIEW

**Comment by nottrobin** [comment]
[run-jekyll script](https://trello.com/c/R2GrXXLn/3095-run-jekyll-script)

**Review by pmahnke — CHANGES_REQUESTED** [review]
@nottrobin 

the `package.json` had some scripts in it

```
  "scripts": {
    "help": "gulp help",
    "develop": "gulp develop",
    "start": "gulp jekyll",
    "test": "gulp test",
    "build": "gulp build",
    "clean": "rm -r build, rm -rf _jekyll/_site"
  },
```

I don't know if that matters...

everything worked until 'run watch --watch-site`

which gave this error

`./run: line 154: env_file: unbound variable`

**Comment by nottrobin** [comment]
Fixed that particular error, but you'll still get an error because the `watch` script isn't defined in `package.json`. To test it out you could try writing one like `"watch": "sleep 10"` or something.

**Review by pmahnke — APPROVED** [review]
worked. 👍

**Pull request merged**
